function Install-ISHWindowsFeature
{
    <#
    ServerManager is expected in Windows Server operating system.
    In a client OS like Windows 7,8 or 10, ServerManager is not available. 
    Instead there is DISM. 
    Server and DISM are much alike but the name of cmdlet, the terms and flow is a bit different.
    With DISM you need to check if a feature is installed before installing it.

    #>
    if(Get-Module ServerManager -ListAvailable)
    {
        $featureNames=@(
            #http://docs.sdl.com/LiveContent/content/en-US/SDL%20Knowledge%20Center%20full%20documentation-v2/GUID-47EC6977-C62C-493E-B6DA-F0A3D0003C9D
            #"Application-Server"
            "AS-NET-Framework"
            "NET-WCF-Services45"
		    "NET-WCF-HTTP-Activation45"
		    "NET-WCF-TCP-PortSharing45"
            #http://docs.sdl.com/LiveContent/content/en-US/SDL%20Knowledge%20Center%20full%20documentation-v2/GUID-F0F2DB60-4C4F-4962-9FC1-AE8D2F1929FE
            "Web-Default-Doc"
            "Web-Dir-Browsing"
            "Web-Http-Errors"
            "Web-Static-Content"
            "Web-Http-Logging"
            "Web-Request-Monitor"
            "Web-Stat-Compression"
            "Web-Dyn-Compression"
            "Web-Net-Ext45"
            "Web-ASP"
            "Web-Asp-Net45"
            "Web-ISAPI-Ext"
            "Web-ISAPI-Filter"
            "Web-Mgmt-Console"
            #http://docs.sdl.com/LiveContent/content/en-US/SDL%20Knowledge%20Center%20full%20documentation-v2/GUID-B06F62DB-9D30-4C2E-8C89-C116BD8F0829
            "AS-WS-Atomic"
            "AS-Incoming-Trans"
            "AS-Outgoing-Trans"
        )
        Install-WindowsFeature -Name $featureNames |Out-Null
    }
    elseif(Get-Module DISM -ListAvailable)
    {
        Write-Warning "DISM module was found instead of ServerManager. This should happen only in non Server operating systems."
        #List generated by Alex Sarafian's working laptop on Windows 8.1
        # Get-WindowsOptionalFeature -Online |Where-Object -Property State -Eq "Enabled"| Select-object -ExpandProperty FeatureName
        $features=@(
            "IIS-WebServerRole"
            "IIS-WebServer"
            "IIS-CommonHttpFeatures"
            "IIS-ApplicationDevelopment"
            "IIS-NetFxExtensibility45"
            "IIS-Security"
            "IIS-RequestFiltering"
            "IIS-Performance"
            "IIS-HttpCompressionDynamic"
            "IIS-WebServerManagementTools"
            "WAS-WindowsActivationService"
            "WAS-ProcessModel"
            "WAS-ConfigurationAPI"
            "IIS-WindowsAuthentication"
            "IIS-StaticContent"
            "IIS-DefaultDocument"
            "IIS-WebSockets"
            "IIS-ASPNET45"
            "IIS-ASP"
            "IIS-ISAPIExtensions"
            "IIS-ISAPIFilter"
            "IIS-BasicAuthentication"
            "IIS-HttpCompressionStatic"
            "IIS-ManagementConsole"
            "IIS-FTPServer"
            "WCF-Services45"
            "WCF-HTTP-Activation45"
            "NetFx4-AdvSrvs"
            "NetFx4Extended-ASPNET45"
        )

        $notInstalledFeatures=$features|ForEach-Object {
            $feature=Get-WindowsOptionalFeature -FeatureName $_ -Online
            if($feature.State -eq "Enabled")
            {
                Write-Warning "$($feature.FeatureName) is already installed"
            }
            else
            {
                Write-Verbose "$($feature.FeatureName) will be installed"
                $feature
            }
        }
        #$notInstalledFeatures|Format-Table
        $notInstalledFeatures| ForEach-Object {
            try
            {
                $featureName=$_.FeatureName
                Enable-WindowsOptionalFeature -FeatureName $featureName -Online -All
                Write-Host "Enabled feature $featureName"
            }
            catch
            {
                Write-Error "Error for $featureName"
                Write-Error "$_"
            }
        }
    }
    else
    {
        Write-Error "Cannot find ServerManager nor DISM powershell modules installed"
    }
}